/**
 * Stack0 Mail SDK
 * Complete email API with support for transactional emails, campaigns, sequences, and more
 * @module @stack0/sdk/mail
 */

// Main client
export { Mail } from "./client";

// Sub-clients (also accessible via Mail instance)
export { Audiences } from "./audiences";
export { Campaigns } from "./campaigns";
export { Contacts } from "./contacts";
export { Domains } from "./domains";
export { Events } from "./events";
export { Sequences } from "./sequences";
export { Templates } from "./templates";

// Types
// Note: Common types (Environment, PaginatedRequest, PaginatedResponse) are exported from shared-types
export type {
  // Email types
  EmailAddress,
  EmailRecipient,
  Attachment,
  EmailStatus,
  Email,
  SendEmailRequest,
  SendEmailResponse,
  SendBatchEmailRequest,
  SendBatchEmailResponse,
  SendBroadcastEmailRequest,
  SendBroadcastEmailResponse,
  GetEmailResponse,
  ListEmailsRequest,
  ListEmailsResponse,
  ResendEmailResponse,
  CancelEmailResponse,
  EmailAnalyticsResponse,
  TimeSeriesAnalyticsRequest,
  TimeSeriesDataPoint,
  TimeSeriesAnalyticsResponse,
  HourlyAnalyticsDataPoint,
  HourlyAnalyticsResponse,
  ListSendersRequest,
  Sender,
  ListSendersResponse,
  // Domain types
  DomainStatus,
  DnsRecord,
  Domain,
  ListDomainsRequest,
  ListDomainsResponse,
  AddDomainRequest,
  AddDomainResponse,
  GetDnsRecordsResponse,
  VerifyDomainResponse,
  DeleteDomainResponse,
  SetDefaultDomainResponse,
  // Template types
  Template,
  CreateTemplateRequest,
  UpdateTemplateRequest,
  ListTemplatesRequest,
  ListTemplatesResponse,
  DeleteTemplateResponse,
  PreviewTemplateRequest,
  PreviewTemplateResponse,
  // Audience types
  Audience,
  CreateAudienceRequest,
  UpdateAudienceRequest,
  ListAudiencesRequest,
  ListAudiencesResponse,
  DeleteAudienceResponse,
  AddContactsToAudienceRequest,
  AddContactsToAudienceResponse,
  RemoveContactsFromAudienceRequest,
  RemoveContactsFromAudienceResponse,
  // Contact types
  ContactStatus,
  MailContact,
  AudienceContact,
  CreateContactRequest,
  UpdateContactRequest,
  ListContactsRequest,
  ListContactsResponse,
  ListAudienceContactsRequest,
  ListAudienceContactsResponse,
  DeleteContactResponse,
  ImportContactsRequest,
  ImportContactsResponse,
  // Campaign types
  CampaignStatus,
  Campaign,
  CreateCampaignRequest,
  UpdateCampaignRequest,
  ListCampaignsRequest,
  ListCampaignsResponse,
  DeleteCampaignResponse,
  SendCampaignRequest,
  SendCampaignResponse,
  PauseCampaignResponse,
  CancelCampaignResponse,
  CampaignStatsResponse,
  // Sequence types
  SequenceStatus,
  SequenceTriggerType,
  SequenceTriggerFrequency,
  SequenceNodeType,
  ConnectionType,
  Sequence,
  SequenceNode,
  SequenceConnection,
  SequenceWithNodes,
  CreateSequenceRequest,
  UpdateSequenceRequest,
  ListSequencesRequest,
  ListSequencesResponse,
  DeleteSequenceResponse,
  PublishSequenceResponse,
  PauseSequenceResponse,
  ResumeSequenceResponse,
  ArchiveSequenceResponse,
  CreateNodeRequest,
  UpdateNodeRequest,
  UpdateNodePositionRequest,
  DeleteNodeResponse,
  SetNodeEmailRequest,
  SetNodeTimerRequest,
  SetNodeFilterRequest,
  SetNodeBranchRequest,
  SetNodeExperimentRequest,
  CreateConnectionRequest,
  DeleteConnectionResponse,
  SequenceEntryStatus,
  SequenceEntry,
  ListSequenceEntriesRequest,
  ListSequenceEntriesResponse,
  AddContactToSequenceRequest,
  RemoveContactFromSequenceRequest,
  RemoveContactFromSequenceResponse,
  SequenceAnalyticsResponse,
  // Event types
  EventProperty,
  EventPropertiesSchema,
  MailEvent,
  CreateEventRequest,
  UpdateEventRequest,
  ListEventsRequest,
  ListEventsResponse,
  DeleteEventResponse,
  TrackEventRequest,
  TrackEventResponse,
  BatchTrackEventsRequest,
  BatchTrackEventsResponse,
  EventOccurrence,
  ListEventOccurrencesRequest,
  ListEventOccurrencesResponse,
  EventAnalyticsResponse,
} from "./types";
